name: CD
concurrency:
  group: cd
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, ci/** ]
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
      - name: Install dependencies client
        run: |
          npm i --force
      - name: Run tests
        run: npm test

  publish:
    name: Release and Publish
    if: github.ref == 'refs/heads/main' && !startsWith( github.event.commits[0].message, 'build(deps-dev)') && !startsWith( github.event.commits[0].message, 'ci(uplift)')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: gembaadvantage/uplift-action@v2.0.1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i --force
          npm run build
          npm publish
